name: LTD
on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - main
      - 'dev/**'
      - 'feature/**'
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: dep-files-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run Linter
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: dep-files-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: test
        run: npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file}}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: dep-files-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: publish Js filename
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: show files
        run: ls
      - name: output filename
        run:  echo "${{needs.build.outputs.script-file}}"
      - name: deploy
        run: echo "deploying.."
      